[phases.setup]
nixPkgs = [
  "python310",
  "git",
  "ffmpeg",
  "postgresql",
  "mesa",
  "mesa.drivers",
  "libglvnd",
  "libGL",
  "libGLU",              
  "xorg.libX11",
  "xorg.libXext",
  "xorg.libSM",
  "zlib"
]

environment = { PIP_NO_CACHE_DIR = "false", PIP_CACHE_DIR = "/tmp/pip-cache" }

[phases.build]
commands = [
  "rm -rf /tmp/pip-cache ~/.cache/pip",
  "git clone --depth 1 -b master https://github.com/Kerleta/yolov5.git yolov5",
  "pip install --upgrade pip setuptools wheel",
  "pip uninstall -y opencv-python opencv-python-headless",
  "pip install opencv-python-headless==4.9.0.80",
  "pip install -r yolov5/requirements.txt",
  "pip install -r requirements.txt"
]

[phases.start]
command = "PYTHONPATH=./yolov5 python file.py"
