[phases.setup]
nixPkgs = [
    "python310",
    "libglvnd",        # Replaces libGL
    "xorg.libSM",      # Correct Xorg package
    "xorg.libXext",    # Correct Xorg package
    "zlib",
    "postgresql",
    "ffmpeg"           # Often needed for OpenCV video processing
]
