[phases.setup]
nixPkgs = ["python310"]

[phases.build]
commands = [
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt",
  "pip install -e yolov5"
]

[phases.start]
command = "gunicorn --bind 0.0.0.0:${PORT:-5000} app.file:app"
