[phases.setup]
nixPkgs = [
    "python310",
    "libglvnd",
    "xorg.libSM",
    "xorg.libXext",
    "xorg.libX11",    # Tambahan penting untuk OpenCV
    "zlib",
    "postgresql",
    "git",
    "ffmpeg"          # Diperlukan untuk video processing
]

[phases.build]
commands = [
    # Gunakan fork Anda
    "git clone https://github.com/Kerleta/yolov5.git ./yolov5",
    "cd yolov5 && git checkout <BRANCH/COMMIT>",
    "cd yolov5 && pip install --upgrade 'setuptools<65.6.0' wheel && pip install -e .",
    "pip install -r requirements.txt"
]

[phases.start]
command = "python file.py"
