[phases.setup]
nixPkgs = [
    "python310",
    "libglvnd",
    "xorg.libSM",
    "xorg.libXext",
    "xorg.libX11",    # Tambahan penting untuk OpenCV
    "zlib",
    "postgresql",
    "git",
    "ffmpeg"          # Diperlukan untuk video processing
]

[phases.build]
commands = [
    # Clone YOLOv5 ke direktori project
    "git clone https://github.com/ultralytics/yolov5.git ./yolov5",
    
    # Install YOLOv5 dengan setuptools versi compatible
    "cd yolov5 && pip install --upgrade 'setuptools<65.6.0' wheel && pip install -e .",
    
    # Install requirements aplikasi
    "pip install -r requirements.txt"
]

[phases.start]
command = "python file.py"
