[phases.setup]
nixPkgs = [
  "python310",
  "git",
  "ffmpeg",
  "postgresql",
  "mesa",
  "mesa.drivers",
  "libglvnd",
  "libGL",
  "libGLU",              
  "xorg.libX11",
  "xorg.libXext",
  "xorg.libSM",
  "zlib"
]

environment = { PIP_NO_CACHE_DIR = "false", PIP_CACHE_DIR = "/tmp/pip-cache", PYTHONPATH = "$PYTHONPATH:./:./yolov5" }

[phases.build]
commands = [
  "rm -rf /tmp/pip-cache ~/.cache/pip",
  "git clone --depth 1 -b master https://github.com/Kerleta/yolov5.git yolov5",
  "pip install --upgrade pip setuptools wheel",
  "pip uninstall -y opencv-python opencv-python-headless",
  "pip install opencv-python-headless==4.7.0.72",
  "pip install cloudinary==1.33.0",
  "pip install flask==2.0.1 werkzeug==2.0.3 flask-cors==3.0.10",
  "pip install -r requirements.txt",
  "cd yolov5 && pip install -e ."
]

[phases.start]
command = "PYTHONPATH=$PYTHONPATH:./yolov5 python file.py"
